version: "3"

services:
  php:
    #image: php:8
    build:
      context: .
      dockerfile: Dockerfile.php
    volumes:
      - .:/var/www/php-py
    tty: true
    ports:
      - 8999
    container_name: php8
  python3:
    #image: python:3.11
    build:
      context: .
      dockerfile: Dockerfile.python
    volumes:
      - .:/var/www/php-py
    tty: true
    ports:
      - 5000
    container_name: python3.11

  ruby:
    build:
      context: .
      dockerfile: Dockerfile.ruby
    volumes:
      - .:/var/www/php-py
    tty: true
    ports:
      - 3000
    container_name: ruby3.2.2
